#ShadowLinks Configuration File
#Please insert the appropriate links after each variable. 
#I recommend you use something such TinyURL for the links. 
Vote: VoteLink
Map: MapLink
Youtube: YoutubeLink
Twitter: Twitter Link
Twitch: Twitch Link
Facebook: Facebook Page Link
Website: Website Link
Instagram: Instagram Link
Teamspeak: Teamspeak IP
Mumble: Mumble IP
Contest: Contest Link
Donate: Donation Link
#Do you want to disable any commands? If so change true to false.
Enable-Vote: true
Enable-Map: true
Enable-Twitch: true
Enable-Website: true
Enable-Facebook: true
Enable-Twitter: true
Enable-Youtube: true
Enable-Instagram: true
Enable-Donate: true
Enable-Teamspeak: true
Enable-Mumble: true
Enable-Notes: true
Enable-Contest: true
#Thank you for using ShadowLinks.